# Generated by Django 5.2 on 2025-05-03 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField()),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('spreadability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('shortDescription', models.CharField()),
                ('longDescription', models.CharField()),
                ('controlMethod', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietyName', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationSusceptability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Orchard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchardName', models.CharField()),
                ('noTreesRow', models.IntegerField()),
                ('noTreesColumn', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.variety')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('partOfPlant', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit')])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='mango_disease_app.disease')),
                ('orchardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.orchard')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietySusceptability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.disease')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.variety')),
            ],
        ),
    ]
