# Generated by Django 5.2 on 2025-05-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0002_alter_orchard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='controlMethod',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='diseaseName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disease',
            name='longDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='shortDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.disease'),
        ),
        migrations.AlterField(
            model_name='locationdisease',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.location'),
        ),
        migrations.AlterField(
            model_name='orchard',
            name='orchardName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='orchardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.orchard'),
        ),
        migrations.AlterField(
            model_name='record',
            name='partOfPlant',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit')], max_length=5),
        ),
        migrations.AlterField(
            model_name='variety',
            name='varietyName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='varietydisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.disease'),
        ),
        migrations.AlterField(
            model_name='varietydisease',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.variety'),
        ),
    ]
