# Generated by Django 5.1.7 on 2025-04-07 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0003_authorcard_degree_alter_authorcard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcard',
            name='BD',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='authorcard',
            name='CI',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
