# Generated by Django 5.2 on 2025-05-07 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0003_alter_disease_controlmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recordedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
