# Generated by Django 5.2 on 2025-05-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0004_alter_record_recordedat_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
