# Generated by Django 5.1.7 on 2025-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0004_authorcard_bd_authorcard_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcard',
            name='student_number',
            field=models.CharField(default='S000000', help_text='Enter CDU Student Number from ID card.', max_length=7),
        ),
        migrations.AlterField(
            model_name='authorcard',
            name='degree',
            field=models.CharField(default='Computer Science', help_text='Enter degree at CDU.', max_length=30),
        ),
        migrations.AlterField(
            model_name='authorcard',
            name='image',
            field=models.ImageField(default='author_images/default.png', help_text='Upload an image or a default empty profile will be provided.', upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='authorcard',
            name='interests',
            field=models.CharField(default='No interests', help_text='Enter a few interests in less than 100 characters.', max_length=100),
        ),
        migrations.AlterField(
            model_name='authorcard',
            name='name',
            field=models.CharField(default='No Name Entered', help_text='Enter contributor name.', max_length=30),
        ),
    ]
