# Generated by Django 5.2 on 2025-05-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0004_alter_record_recordedat'),
        ('mango_disease_app', '0005_remove_userprofile_name'),
    ]

    operations = [
    ]
