# Generated by Django 5.1.7 on 2025-04-08 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0005_authorcard_student_number_alter_authorcard_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorcard',
            name='BD',
        ),
        migrations.RemoveField(
            model_name='authorcard',
            name='CI',
        ),
        migrations.AddField(
            model_name='authorcard',
            name='bigPicture_detailOriented',
            field=models.SmallIntegerField(default=5, help_text='0 is for focus on big picture, 10 is for focus on details.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='authorcard',
            name='collaborator_independent',
            field=models.SmallIntegerField(default=5, help_text='0 is for a strong collaborator, 10 is for most independent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='authorcard',
            name='communicator_listener',
            field=models.SmallIntegerField(default=5, help_text='0 is for a strong communicator, 10 is for a strong listener.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='authorcard',
            name='creative_practical',
            field=models.SmallIntegerField(default=5, help_text='0 is for most creative, 10 is for most practical.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
