# Generated by Django 5.2 on 2025-04-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0006_remove_authorcard_bd_remove_authorcard_ci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name Entered', help_text='Enter disease or pest name.', max_length=30)),
            ],
        ),
    ]
