# Generated by Django 5.2 on 2025-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0006_merge_20250507_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(default='disease_images/defaulyt.JPG', upload_to='disease_images/'),
        ),
    ]
