# Generated by Django 5.2 on 2025-04-09 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0007_diseaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseitem',
            name='control',
            field=models.TextField(default='No control method given', help_text='Method(s) of controlling or eliminating the disease / pest.'),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='image',
            field=models.ImageField(default='author_images/default_disease.jpg', help_text='Upload an image or a default disease (Anthracnose) will be provided.', upload_to='disease_images/'),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='ldesc',
            field=models.TextField(default='No description given', help_text='Enter a long description of the disease or pest to be displayed on an individual page.'),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='pest',
            field=models.BooleanField(default=False, help_text='Set to TRUE if this is a pest, FALSE if this is a disease.'),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='sdesc',
            field=models.TextField(default='No description given', help_text='Enter a short description of the disease or pest to be displayed on a list.'),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='severity',
            field=models.SmallIntegerField(default=1, help_text='Severity of disease / pest on a scale from from 1 to 10, with 10 being most severe.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='diseaseitem',
            name='spreadability',
            field=models.SmallIntegerField(default=1, help_text='How quickly the disease / pest spreads on a scale from from 1 to 10, with 10 being the fastest.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
