# Generated by Django 5.1.7 on 2025-04-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0008_diseaseitem_control_diseaseitem_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorCard',
        ),
    ]
