# Generated by Django 5.2 on 2025-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0008_alter_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='type',
            field=models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease')], default='Disease', max_length=7),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='Active', max_length=8),
        ),
    ]
