# Generated by Django 5.2 on 2025-05-08 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0009_disease_type_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchard',
            name='area',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='numberOfTreesChecked',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='numberOfTreesInfected',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
