# Generated by Django 5.2 on 2025-04-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0009_delete_authorcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseItem',
        ),
    ]
