# Generated by Django 5.2 on 2025-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0010_orchard_area_record_numberoftreeschecked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hemisphere',
            field=models.CharField(choices=[('north', 'Northern'), ('south', 'Southern')], default='south', max_length=5),
        ),
    ]
