# Generated by Django 5.2 on 2025-04-30 07:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mango_disease_app', '0010_delete_diseaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('diseaseID', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseName', models.CharField()),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('spreadability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('shortDescription', models.CharField()),
                ('longDescription', models.CharField()),
                ('controlMethod', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('varietyID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susecptability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.disease')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Orchard',
            fields=[
                ('orchardID', models.AutoField(primary_key=True, serialize=False)),
                ('orchardName', models.CharField()),
                ('noTreesRow', models.IntegerField()),
                ('noTreesColumn', models.IntegerField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.location')),
                ('varietyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.variety')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('recordedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('partOfPlant', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit')])),
                ('orchardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.orchard')),
            ],
        ),
        migrations.CreateModel(
            name='RecordDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.disease')),
                ('recordID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.record')),
            ],
        ),
        migrations.CreateModel(
            name='OrchardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.orchard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyDiseaseSusceptible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.disease')),
                ('varietyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mango_disease_app.variety')),
            ],
        ),
    ]
