# Generated by Django 5.2 on 2025-05-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0011_location_hemisphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='Active', max_length=8, null=True)),
                ('partOfPlant', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit')], max_length=5, null=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.disease')),
                ('orchard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.orchard')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.case'),
        ),
    ]
