# Generated by Django 5.2 on 2025-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='varietyName',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
