# Generated by Django 5.2 on 2025-05-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0012_case_record_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='record',
            name='orchardID',
        ),
        migrations.RemoveField(
            model_name='record',
            name='partOfPlant',
        ),
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.AlterField(
            model_name='record',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.case'),
        ),
    ]
