# Generated by Django 5.2 on 2025-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0012_variety_varietyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='diseases',
            field=models.ManyToManyField(related_name='records', to='mango_disease_app.disease'),
        ),
        migrations.DeleteModel(
            name='RecordDisease',
        ),
    ]
