# Generated by Django 5.2 on 2025-05-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0013_record_diseases_delete_recorddisease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diseases',
        ),
        migrations.AddField(
            model_name='record',
            name='disease',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='mango_disease_app.disease'),
            preserve_default=False,
        ),
    ]
