# Generated by Django 5.2 on 2025-05-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0013_remove_record_disease_remove_record_orchardid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='orchard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.orchard'),
        ),
        migrations.AlterField(
            model_name='record',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_disease_app.case'),
        ),
    ]
