# Generated by Django 5.2 on 2025-05-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0014_remove_record_diseases_record_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrchardUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
