# Generated by Django 5.2 on 2025-05-21 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0014_record_orchard_alter_record_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varietydisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='varietydisease',
            name='variety',
        ),
        migrations.AddField(
            model_name='location',
            name='locationSusceptability',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='variety',
            name='varietySusceptability',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='LocationDisease',
        ),
        migrations.DeleteModel(
            name='VarietyDisease',
        ),
    ]
