# Generated by Django 5.2 on 2025-05-03 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0015_delete_orcharduser_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisease',
            old_name='susecptability',
            new_name='locationSusecptability',
        ),
        migrations.AddField(
            model_name='varietydiseasesusceptible',
            name='varietySusecptability',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
