# Generated by Django 5.2 on 2025-05-21 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0015_remove_varietydisease_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationSusceptability',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
