# Generated by Django 5.2 on 2025-05-21 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0016_alter_location_locationsusceptability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='varietySusceptability',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
