# Generated by Django 5.2 on 2025-05-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0017_orchard_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VarietyDiseaseSusceptible',
            new_name='VarietyDisease',
        ),
    ]
