# Generated by Django 5.2 on 2025-05-28 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0017_alter_variety_varietysusceptability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchard',
            name='area',
            field=models.FloatField(help_text='Enter in acres.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
