# Generated by Django 5.2 on 2025-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_disease_app', '0018_rename_varietydiseasesusceptible_varietydisease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisease',
            old_name='locationSusecptability',
            new_name='locationSusceptability',
        ),
        migrations.RenameField(
            model_name='varietydisease',
            old_name='varietySusecptability',
            new_name='varietySusceptability',
        ),
    ]
